- name: Log into private registry
  docker_login:
      username: sayedshalabi
      password: 01143576873sa
      reauthorize: yes
  become: yes

- name: Build Image
  docker_image:
     name: "{{ name_of_image }}"
     build:
       path: "{{ path_of_docker }}"
     source: build
     push: yes
  become: yes
  become_user: root
